---
# tasks file for webserver
- name: Ensure nginx is installed
  ansible.builtin.package:
    name: nginx
    state: present

- name: Ensure nginx is started at boot
  ansible.builtin.service:
    name: nginx
    enabled: true
    state: started

- name: Copy HTTPS configuration file
  ansible.builtin.copy:
    src: files/https.conf
    dest: /etc/nginx/conf.d/https.conf
    owner: root
    group: root
    mode: '0644'
  notify: reload nginx

- name: Ensure the nginx configuration is updated for example.internal
  ansible.builtin.copy:
    src: files/example.internal.conf
    dest: /etc/nginx/conf.d/example.internal.conf
    owner: root
    group: root
    mode: '0644'
  notify: reload nginx

- name: Create web root directory
  ansible.builtin.file:
    path: /var/www/example.internal/html
    state: directory
    owner: root
    group: root
    mode: '0755'
    setype: httpd_sys_content_t

- name: Upload index.html
  ansible.builtin.copy:
    src: files/index.html
    dest: /var/www/example.internal/html/index.html
    owner: root
    group: root
    mode: '0644'
    setype: httpd_sys_content_t

- name: Ensure web root exists
  ansible.builtin.file:
    path: /var/www/example.internal/html
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Upload templated nginx configuration
  ansible.builtin.template:
    src: templates/example.internal.conf.j2
    dest: /etc/nginx/conf.d/example.internal.conf
    owner: root
    group: root
    mode: '0644'

- name: Ensure the /etc/pki/nginx directory exists
  ansible.builtin.file:
    path: /etc/pki/nginx
    state: directory
    mode: "0755"
    owner: root

- name: Ensure we have a /etc/pkig/nginx/private directory
  ansible.builtin.file:
    path: /etc/pki/nginx/private
    state: directory
    mode: "0700"
    owner: root

- name: Ensure we have necessary software installed
  ansible.builtin.package:
    name: python3-cryptography
    state: present

- name: Ensure we have a private key for our certificate
  community.crypto.openssl_privatekey:
    path: /etc/pki/nginx/private/server.key

- name: Create a self-signed certificate
  community.crypto.x509_certificate:
    path: /etc/pki/nginx/server.crt
    privatekey_path: /etc/pki/nginx/private/server.key
    provider: selfsigned