---
- name: Install and enable MariaDB server
  hosts: dbserver
  become: true
  tasks:
    - name: Ensure MariaDB-server is installed
      ansible.builtin.package:
        name: mariadb-server
        state: present

    - name: Ensure MariaDB service is started and enabled at boot
      ansible.builtin.service:
        name: mariadb
        state: started
        enabled: true
