---
- name: Configure MariaDB with database and user
  hosts: dbserver
  become: true
  tasks:
    - name: Ensure MariaDB server is installed
      ansible.builtin.package:
        name: mariadb-server
        state: present

    - name: Ensure MariaDB service is started and enabled
      ansible.builtin.service:
        name: mariadb
        state: started
        enabled: true

    - name: Ensure Python MySQL library is installed
      ansible.builtin.package:
        name: python3-PyMySQL
        state: present

    - name: Create a database called webappdb
      community.mysql.mysql_db:
        name: webappdb
        state: present
        login_unix_socket: /var/lib/mysql/mysql.sock

    - name: Create a user for the web application
      community.mysql.mysql_user:
        name: webappuser
        password: secretpassword
        priv: 'webappdb.*:ALL'
        host: localhost
        state: present
        login_unix_socket: /var/lib/mysql/mysql.sock
